language: php

php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"

before_script:
 - sudo apt-get update
 - sudo apt-get install php5-cli php5-common php-pear
 - composer self-update
 - composer install


script: phpunit