language: php

php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  
matrix:
  fast_finish: true
  
before_script:
 - phpenv config-rm xdebug.ini
 - composer self-update
 - composer install

script: phpunit